version: '3.8'

services:
  mysql:
    image: yishuihang/mysql-server-5.8
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      - ALL_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=admin
    restart: unless-stopped
